"""Markdown baseline report generation for a scan run."""

from datetime import datetime

from sqlalchemy.orm import Session

from app.models.db import Finding, Run
from app.services.checks.base import (
    CRITICAL,
    HIGH,
    INFORMATIONAL,
    LOW,
    MEDIUM,
    SEVERITY_ORDER,
)

# Rough ease-of-fix weighting for the remediation priority list — lower is easier.
_EASE = {
    "iam_root_mfa": 0, "iam_console_no_mfa": 1, "s3_account_block_public_access": 1,
    "ec2_ebs_default_encryption": 1, "iam_password_policy": 1, "ec2_sg_open_ipv4": 2,
    "ec2_sg_open_ipv6": 2, "guardduty_enabled": 1, "securityhub_enabled": 1,
}


def generate_report(db: Session, run_id: str) -> str | None:
    run = db.query(Run).filter(Run.id == run_id).first()
    if not run:
        return None

    findings = (
        db.query(Finding)
        .filter(Finding.run_id == run_id)
        .all()
    )
    findings.sort(key=lambda f: SEVERITY_ORDER.get(f.severity, 99))

    counts = {sev: 0 for sev in (CRITICAL, HIGH, MEDIUM, LOW, INFORMATIONAL)}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1

    account_id = findings[0].account_id if findings else "unknown"
    date = datetime.utcnow().strftime("%Y-%m-%d")
    engines = ", ".join(run.engines or []) or "unknown"

    lines: list[str] = []
    lines.append("# RhinoScan Security Assessment")
    lines.append(f"**Client:** {run.target}")
    lines.append(f"**Target:** {run.target} ({account_id})")
    lines.append(f"**Engines:** {engines}")
    lines.append(f"**Date:** {date}")
    lines.append(f"**Run ID:** {run_id}")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append(
        f"{counts[CRITICAL]} critical, {counts[HIGH]} high, {counts[MEDIUM]} medium "
        f"findings across {len(findings)} total findings."
    )
    lines.append("")

    for sev in (CRITICAL, HIGH, MEDIUM):
        group = [f for f in findings if f.severity == sev]
        lines.append(f"## {sev} Findings")
        if not group:
            lines.append("_None._")
        for f in group:
            lines.append(f"### {f.title}")
            lines.append(f"- **Source:** {f.origin}")
            lines.append(f"- **Category:** {f.category}")
            lines.append(f"- **Resource:** `{f.resource}`")
            lines.append(f"- **Check:** `{f.source}`")
            lines.append(f"- **Detail:** {f.description}")
            lines.append(f"- **Remediation:** {f.remediation}")
            lines.append("")
        lines.append("")

    lines.append("## Remediation Priority List")
    lines.append("Ordered by severity, then ease of fix.")
    lines.append("")
    actionable = [f for f in findings if f.severity != INFORMATIONAL]
    actionable.sort(key=lambda f: (
        SEVERITY_ORDER.get(f.severity, 99), _EASE.get(f.source, 5),
    ))
    for i, f in enumerate(actionable, 1):
        lines.append(f"{i}. **[{f.severity}]** {f.title} — {f.remediation}")
    if not actionable:
        lines.append("_No actionable findings._")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by RhinoScan — Gray Rhino Security*")
    return "\n".join(lines)
